const images = {
    logoFCCC: require('../assets/images/logoFCCC.png'),
    //home: require('../Images/home.jpg'),
    //iglesia: require('../Images/iglesia.jpg'),
    pastores: require('../assets/images/Pastores3.jpg'),
    iglesia: require('../assets/images/iglesia.jpg'),
    iglesiaYmca: require('../assets/images/iglesiaYmca.jpg'),
    calendarImage: require('../assets/images/calendarScreen.jpg'),
    ninos: require('../assets/images/ninos.jpg'),
    ninos2: require('../assets/images/ninos2.jpg'),
    bautizo1: require('../assets/images/bautizo1.jpg'),
    bautizo2: require('../assets/images/bautizo2.jpg'),
    clase: require('../assets/images/clase.jpeg'),
    jovenes: require('../assets/images/jovenes.jpeg'),
    ministries: require('../assets/images/homePray.jpg'),
    findUs: require('../assets/images/GoogleMaps.jpg'),
    iconoPhone: require('../assets/images/icon-phone.png'),
    iconHeart: require('../assets/images/icon-heart.png'),
    iconBible: require('../assets/images/icon-bible.png'),
    give: require('../assets/images/give.jpg'),
    calendar: require('../assets/images/calendar.jpg'),
    prayerRequest: require('../assets/images/homeRequest.jpg'),
    churchIcon: require('../assets/images/church-icon.png'),
    calendarScreen: require('../assets/images/ninos.jpg'),
    findUsIcon: require('../assets/images/find-icon.png'),
    servicio: require('../assets/images/servicio.jpg'),
    iconEmail: require('../assets/images/icon-email.png'),
    background: require('../assets/images/BG.png'),
    regaloPerfecto: require('../assets/images/Drama.jpg'),
    boss: require('../assets/images/Boss.jpg'),
    maelo: require('../assets/images/maelo.jpg'),
    bannerAyuno: require('../assets/images/FCCCBannerAyuno.png'),
    imagenAyuno1: require('../assets/images/ayuno1.jpg'),
    mensajesPastorales: require('../assets/images/MensajesPastorales.png'),
    cafeconmipareja: require('../assets/images/Cafeconmipareja.png'),
    Diosessoberano: require('../assets/images/DiosesSoberano.png'),
    seaLaLuz: require('../assets/images/seaLaLuz.png'),
    movieLikeArrows: require('../assets/images/movieLikeArrows.jpg'),
    oradSinCesar: require('../assets/images/OradSinCesar.png'),
    PazEnLaTormenta: require('../assets/images/Pazenlatormenta.png'),
    DiosNoConocido: require('../assets/images/DiosNoConocido.jpeg'),
    Queso: require('../assets/images/Quienmoviomiqueso.jpeg'),
    consumadoes: require('../assets/images/consumadoes.jpeg'),
    jesuselcaminolaverdadylavida: require('../assets/images/jesuselcaminolaverdadylavida.jpeg'),
    analfabetismoBiblico: require('../assets/images/analfabetismoBiblico.png'),
    viajeEspiritual: require('../assets/images/tierra.jpeg'),
    estadQuietos: require('../assets/images/EstadQuietos.png'),
    DiosPeleaNuestrasBatallas: require('../assets/images/DiosPeleaNuestrasBatallas.png'),
    unaPuertaAbierta: require('../assets/images/unaPuertaAbierta.jpeg'),
    elGozoDelSenor: require('../assets/images/ElGozoDelSenor.jpeg'),
    presenciaDeDios: require('../assets/images/PresenciadeDios.png'),
    americaChristian: require('../assets/images/USA-flag-Christian.jpg'),

}

export default images;

