const images = {
    logoFCCC: require('../assets/images/logoFCCC.png'),
    //home: require('../Images/home.jpg'),
    //iglesia: require('../Images/iglesia.jpg'),
    pastores: require('../assets/images/Pastores3.jpg'),
    iglesia: require('../assets/images/iglesia.jpg'),
    iglesiaYmca: require('../assets/images/iglesiaYmca.jpg'),
    //calendarImage: require('../Images/calendarScreen.jpg'),
    // ninos: require('../Images/ninos.jpg'),
    // ninos2: require('../Images/ninos2.jpg'),
    // bautizo1: require('../Images/bautizo1.jpg'),
    // bautizo2: require('../Images/bautizo2.jpg'),
    // clase: require('../Images/clase.jpeg'),
    // jovenes: require('../Images/jovenes.jpeg'),
    ministries: require('../assets/images/homePray.jpg'),
    findUs: require('../assets/images/GoogleMaps.jpg'),
    // iconoPhone: require('../Images/Icons/icon-phone.png'),
    iconHeart: require('../assets/images/icon-heart.png'),
    iconBible: require('../assets/images/icon-bible.png'),
    give: require('../assets/images/give.jpg'),
    calendar: require('../assets/images/calendar.jpg'),
    prayerRequest: require('../assets/images/homeRequest.jpg'),
    churchIcon: require('../assets/images/church-icon.png'),
    // calendarScreen: require('../Images/ninos.jpg'),
    // findUsIcon: require('../Images/Icons/find-icon.png'),
    // servicio: require('../Images/servicio.jpg'),
    // iconEmail: require('../Images/Icons/icon-email.png'),
    background: require('../assets/images/BG.png'),
}

export default images;

